### ISSUE TITLE
wrong spelling

### ISSUE THREAD

**Issue by ChrisMicro** [esptiny86/espsynth86#4]
fatal error: defines.h: No such file or directory
 #include "defines.h"
                     ^
compilation terminated.

**Comment by badgeek** [comment]
where is this located ?

**Comment by ChrisMicro** [comment]
~/Arduino/libraries/espsynth86$

**Comment by ChrisMicro** [comment]
Seems to be an issue with capital letters.
There is "Defines.h" in the src-folter
but not "defines.h"

**Comment by badgeek** [comment]
but all includes is Defines.h i use find text on directories

**Comment by badgeek** [comment]
i think you need create symlink to the src folder to ~/Arduino/libraries/espsynth86
